# Generated by Django 2.2.5 on 2019-09-25 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('weapon_range', models.PositiveIntegerField(default=0)),
                ('damage', models.PositiveIntegerField(default=0)),
                ('attribute', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('max_health', models.PositiveIntegerField(default=0)),
                ('back_equip', models.ManyToManyField(related_name='_fighter_back_equip_+', to='GridLocked.Equipment')),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('left_equip', models.ManyToManyField(related_name='_fighter_left_equip_+', to='GridLocked.Equipment')),
                ('right_equip', models.ManyToManyField(related_name='_fighter_right_equip_+', to='GridLocked.Equipment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
