# Generated by Django 2.2.5 on 2019-09-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='attribute',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
