# Generated by Django 2.2.5 on 2019-09-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0002_auto_20190925_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': ['Equipment']},
        ),
    ]
