# Generated by Django 2.2.5 on 2019-09-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0004_auto_20190925_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='attribute',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
