# Generated by Django 2.2.5 on 2019-09-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0005_auto_20190925_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='back_equip',
        ),
        migrations.AddField(
            model_name='fighter',
            name='back_equip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='GridLocked.Equipment'),
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='left_equip',
        ),
        migrations.AddField(
            model_name='fighter',
            name='left_equip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='GridLocked.Equipment'),
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='right_equip',
        ),
        migrations.AddField(
            model_name='fighter',
            name='right_equip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='GridLocked.Equipment'),
        ),
    ]
