# Generated by Django 2.2.5 on 2019-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0006_auto_20190925_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='min_range_offest',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
