# Generated by Django 2.2.5 on 2019-09-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0008_equipment_area_of_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='damage',
            field=models.IntegerField(default=0),
        ),
    ]
