# Generated by Django 2.2.5 on 2019-09-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0009_auto_20190925_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='damage',
        ),
        migrations.AddField(
            model_name='equipment',
            name='force',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GridLocked.Attribute'),
        ),
    ]
