# Generated by Django 2.2.5 on 2019-09-25 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0010_auto_20190925_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GridLocked.Attribute'),
        ),
    ]
