# Generated by Django 2.2.5 on 2019-09-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0011_fighter_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='nemesis_attribute',
            field=models.ManyToManyField(blank=True, null=True, to='GridLocked.Attribute'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='force',
            field=models.IntegerField(default=0),
        ),
    ]
