# Generated by Django 2.2.5 on 2019-09-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0012_auto_20190925_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='nemesis_attribute',
            field=models.ManyToManyField(blank=True, to='GridLocked.Attribute'),
        ),
    ]
