# Generated by Django 2.2.5 on 2019-09-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0015_auto_20190925_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='bonus_vs',
        ),
        migrations.AddField(
            model_name='fighter',
            name='weak_vs',
            field=models.ManyToManyField(blank=True, related_name='_fighter_weak_vs_+', to='GridLocked.Attribute'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='strong_vs',
            field=models.ManyToManyField(blank=True, related_name='_fighter_strong_vs_+', to='GridLocked.Attribute'),
        ),
    ]
