# Generated by Django 2.2.5 on 2019-09-27 16:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0017_auto_20190925_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='tough_vs',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='weak_vs',
        ),
        migrations.AddField(
            model_name='fighter',
            name='acid_value',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='fighter',
            name='energy_value',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='fighter',
            name='metal_value',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='fighter',
            name='quantum_value',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='attribute',
            field=models.CharField(choices=[('E', 'ENERGY'), ('A', 'ACID'), ('M', 'METAL'), ('Q', 'QUANTUM')], default='E', max_length=1),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
