# Generated by Django 2.2.5 on 2019-10-10 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GridLocked', '0019_auto_20191008_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='back_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='GridLocked.Equipment'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='left_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='GridLocked.Equipment'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='right_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='GridLocked.Equipment'),
        ),
    ]
